name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Check-out des Repositorys
      - name: Checkout code
        uses: actions/checkout@v3

      # Setze Docker Buildx ein
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login bei GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Baue das Docker-Image und pushe es
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/quarkus-service-2:latest # Ersetze "my-service" mit dem Namen deines Services
